version: '3.8'
networks:
  rmoff_kafka:
    name: rmoff_kafka
  my-network:
    driver: bridge

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks: 
      - rmoff_kafka
      - my-network

  db_initializer:
    build:
      context: ./mongodb
    depends_on:
      - mongodb
  producer:
    container_name: producer
    build: ./api/producer
    ports:
      - "8000:8000"
    depends_on:
      - kafka
      - zookeeper
      - mongodb
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
    networks: 
      - rmoff_kafka
      - my-network
    
  consumer:
    build: ./api/consumer
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
    networks: 
      - rmoff_kafka
    depends_on:
      - kafka
      - zookeeper
      - mongodb

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks: 
      - rmoff_kafka

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "19092:19092"
    networks: 
      - rmoff_kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:19092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data

  kafka-setup:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-setup
    networks: 
      - rmoff_kafka
    depends_on:
      - kafka
    command: >
      bash -c "
      cub kafka-ready -b kafka:9092 1 60 &&
      kafka-topics --create --if-not-exists --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 --topic invoices
      "

  spark:
    image: bitnami/spark:latest
    environment:
      SPARK_MODE: master
    ports:
      - "8080:8080"
    volumes:
      - ./Users/umararshid/Documents/Projects/Invoice E2E DE/checkpoints:/path/to/checkpoint/dir
    networks: 
      - rmoff_kafka

  streamlit:
    build: ./streamlit
    ports:
      - "8501:8501"
    depends_on:
      - mongodb
      - producer
    networks: 
      - rmoff_kafka
      - my-network
volumes:
  kafka_data:
  mongodb_data:
  